[project]
name = "curso-tds"
version = "0.1.0"
description = ""
authors = [
    {name = "rbonifacio",email = "rbonifacio123@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
mypy = "^2.3.1"
ruff = "^0.16.5"


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]


[tool.mypy]
python_version = "3.14"
files = ["src", "tests"]
strict = true


[tool.ruff]
target-version = "py314"
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
